### PR TITLE
nLogin Migrator FIX

### PR DESCRIPTION
**Pull request by LucaFontanot**
nLogin uses Bcrypt and the table schema is

```CREATE TABLE nlogin (ai INTEGER PRIMARY KEY, `last_name` VARCHAR(255) NOT NULL, `unique_id` VARCHAR(32) UNIQUE, `mojang_id` VARCHAR(32) UNIQUE, `bedrock_id` VARCHAR(32) UNIQUE, `password` VARCHAR(255), `last_ip` VARCHAR(60) DEFAULT '127.0.0.1', `last_seen` TIMESTAMP, `creation_date` TIMESTAMP, `email` VARCHAR(255), `discord` VARCHAR(255), `settings` TEXT)```

### CODE REVIEW

**Comment by professorparabellum** [comment]
bump

**Review by kyngs — APPROVED** [review]

**Comment by professorparabellum** [comment]
im pretty positive that the schema is still incorrect, im not sure if you're using the premium version or not but on our server this is the following schema:
image
so, for us its `last_ip`. But on this commit it's changed to `last_address`, I'm not sure why it's like this. Maybe they updated the schema on newer builds.
@LucaFontanot , Can you go into mysql, do `USE <nlogin db>;`, `SHOW TABLES;`, and then `DESCRIBE nlogin;`? I want to see how the schema looks like on your end. We're using the proxy version of nlogin and librelogin, perhaps you are using paper?

**Comment by LucaFontanot** [comment]
@professorparabellum i have that schema from SQLITE storage engine. Maybe SQL has a different schema. It seems only the `last_seen` and  `last_login` are in conflict. So we should add a if conditional on the migrator, or we need to separate SQL and SQLITE

**Comment by professorparabellum** [comment]
I think the best option is to somehow configure what schema to use. In the config.yml file you're able to change the schema to whatever you want, and I think what happened was they changed it at some point (our config is more than a year old):
```
  table:
    account:
      # Sets the name of the nLogin accounts table.
      # - Don't change this information if you don't know what you are doing!
      table-name: "nlogin"

      # Sets the name of the columns.
      # - Don't change this information if you don't know what you are doing!
      columns:
        ai: "ai"
        last-name: "last_name"
        unique-id: "unique_id"
        mojang-id: "mojang_id"
        bedrock-id: "bedrock_id"
        password: "password"
        premium: "premium"
        last-ip: "last_ip"
        last-login: "last_login"
        creation-date: "creation_date"
        email: "email"
        discord: "discord"
        settings: "settings"
```

**Comment by LucaFontanot** [comment]
@professorparabellum I don't know then how this should be handled. in the librelogin config there is no migrator specific options. I would assume that the best option is to only implement the default values, maybe also a check for older ones. 

If someone has customized the colum names I think is reasonable to edit the plugin yourself as it is open source.

**Comment by professorparabellum** [comment]
i think the best option would be to have a way to configure the column names for migration:
https://docs.nickuc.com/nlogin/config/template 
under `database.table.account.columns` you can see what im talking about:
```
...
      # Sets the name of the columns.
      # - Don't change this information if you don't know what you are doing!
      columns:
        ai: "ai"
        last-name: "last_name"
        unique-id: "unique_id"
        mojang-id: "mojang_id"
        bedrock-id: "bedrock_id"
        password: "password"
        premium: "premium"
        last-ip: "last_ip"
        last-seen: "last_seen"
        creation-date: "creation_date"
        email: "email"
        discord: "discord"
        settings: "settings"
```
by default nlogin allows you to change them inside of the config, our db is quite old so i think its possible that we are using old column names.

**Pull request merged**
